"""
Anthropic Agent SDK configuration for Consulting PM Agent (Claudie) — Every Inc.
Generated by ai-first-kit v1.0 | 2026-04-02
"""
from pathlib import Path
from claude_agent_sdk import Agent, tools

ORG_DESIGN_ROOT = Path(__file__).resolve().parent.parent.parent
PRIMER_PATH = ORG_DESIGN_ROOT / "AGENT-PRIMER.md"
PROMPT_PATH = ORG_DESIGN_ROOT / "agents/consulting-pm/system-prompt.md"

consulting_pm_agent = Agent(
    name="consulting-pm",
    model="claude-sonnet-4-20250514",
    instructions=PROMPT_PATH.read_text(),
    tools=[
        tools.computer,  # Document generation, template creation
    ],
    handoff_description=(
        "Claudie — consulting PM agent. Manages engagement logistics: client "
        "onboarding, weekly status reports (saves Natalia 14 hrs/week), training "
        "preparation, deliverable tracking. Drafts client-facing materials for "
        "Natalia's review. Strict data isolation between client engagements."
    ),
)

# Usage:
# from config_anthropic_sdk import consulting_pm_agent
# result = consulting_pm_agent.run("Generate status report for engagement: ...")
