"""
Anthropic Agent SDK configuration for Editorial Quality Agent — Every Inc.
Generated by ai-first-kit v1.0 | 2026-04-02
"""
from pathlib import Path
from claude_agent_sdk import Agent

ORG_DESIGN_ROOT = Path(__file__).resolve().parent.parent.parent
PRIMER_PATH = ORG_DESIGN_ROOT / "AGENT-PRIMER.md"
PROMPT_PATH = ORG_DESIGN_ROOT / "agents/editorial-quality/system-prompt.md"

editorial_quality_agent = Agent(
    name="editorial-quality",
    model="claude-sonnet-4-20250514",
    instructions=PROMPT_PATH.read_text(),
    tools=[],  # Read-only analysis agent — no tool use needed
    handoff_description=(
        "Editorial quality gate agent. Reviews article drafts against "
        "Kate Lee's three rigor tests, Katie Parrott's AI tells detection, "
        "and builder credibility checks. Returns structured assessment."
    ),
)

# Usage:
# from config_anthropic_sdk import editorial_quality_agent
# result = editorial_quality_agent.run("Review this article draft: ...")
