"""
Anthropic Agent SDK configuration for Content Distribution Agent — Every Inc.
Generated by ai-first-kit v1.0 | 2026-04-02
"""
from pathlib import Path
from claude_agent_sdk import Agent

ORG_DESIGN_ROOT = Path(__file__).resolve().parent.parent.parent
PRIMER_PATH = ORG_DESIGN_ROOT / "AGENT-PRIMER.md"
PROMPT_PATH = ORG_DESIGN_ROOT / "agents/content-distribution/system-prompt.md"

content_distribution_agent = Agent(
    name="content-distribution",
    model="claude-sonnet-4-20250514",
    instructions=PROMPT_PATH.read_text(),
    tools=[],  # Draft generation agent — no external tool use needed
    handoff_description=(
        "Content distribution agent. Generates social media posts from published "
        "Every articles, matching each author's voice. Runs quality gate checks "
        "and queues drafts for Anthony's review. Never posts directly."
    ),
)

# Usage:
# from config_anthropic_sdk import content_distribution_agent
# result = content_distribution_agent.run("Generate social posts for article: ...")
