"""
Anthropic Agent SDK configuration for Compound Engineering Agent — Every Inc.
Generated by ai-first-kit v1.0 | 2026-04-02
"""
from pathlib import Path
from claude_agent_sdk import Agent, tools

ORG_DESIGN_ROOT = Path(__file__).resolve().parent.parent.parent
PRIMER_PATH = ORG_DESIGN_ROOT / "AGENT-PRIMER.md"
PROMPT_PATH = ORG_DESIGN_ROOT / "agents/compound-engineering/system-prompt.md"

compound_engineering_agent = Agent(
    name="compound-engineering",
    model="claude-sonnet-4-20250514",
    instructions=PROMPT_PATH.read_text(),
    tools=[
        tools.computer,       # File system read/write, code generation
        tools.bash,           # Shell commands for tests, lint, git
        tools.text_editor,    # Code editing
    ],
    handoff_description=(
        "Compound engineering execution agent. Executes the Plan→Work→Review→Compound "
        "cycle: generates code per approved plans, runs 14-agent review pipeline, "
        "auto-fixes P1 findings, and produces compound artifacts (docs/solutions/, "
        "CLAUDE.md updates). Operates within a single product GM's domain."
    ),
)

# Usage:
# from config_anthropic_sdk import compound_engineering_agent
# result = compound_engineering_agent.run("Execute this plan: ...")
