"""
Anthropic Agent SDK configuration for Product GM Agent — Every Inc.
Generated by ai-first-kit v1.0 | 2026-04-02
"""
from pathlib import Path
from claude_agent_sdk import Agent, tools

ORG_DESIGN_ROOT = Path(__file__).resolve().parent.parent.parent
PRIMER_PATH = ORG_DESIGN_ROOT / "AGENT-PRIMER.md"
PROMPT_PATH = ORG_DESIGN_ROOT / "agents/product-gm/system-prompt.md"

product_gm_agent = Agent(
    name="product-gm",
    model="claude-sonnet-4-20250514",
    instructions=PROMPT_PATH.read_text(),
    tools=[
        tools.computer,       # File system, code generation, docs
        tools.bash,           # Shell commands for tests, lint, git
        tools.text_editor,    # Code and document editing
        tools.web_search,     # Research and information gathering
    ],
    handoff_description=(
        "Full-stack Product GM agent. Writes PRDs and plans, executes the "
        "Plan→Work→Review→Compound cycle, triages 14-agent review findings, "
        "prepares merge requests for GM approval, and produces compound "
        "artifacts. Template agent for Kieran/Cora, Naveen/Monologue, "
        "Yash/Sparkle, Danny/Spiral."
    ),
)

# Usage:
# from config_anthropic_sdk import product_gm_agent
# result = product_gm_agent.run("Write a PRD for feature: ...")
